freebsd_instance:
  image_family: freebsd-12-1

build_package_test_task:
  install_script:
    - pkg install -y gnupg
    - python3 -m ensurepip
    - python3 -m pip install -r requirements.txt
    - export PATH=$PATH:$HOME/.local/bin/
    - echo $PATH

  build_package_test_script:
    - python3 -m jill install --confirm --upstream Official
    - julia -e 'using InteractiveUtils; versioninfo()'
    - python3 -m jill install 1.0 --confirm --upstream Official
    - julia -e 'using InteractiveUtils; versioninfo()'
    - julia-1 -e 'using InteractiveUtils; versioninfo()'
    - julia-1.0 -e 'using InteractiveUtils; versioninfo()'
    - python3 -m jill install latest --confirm --upstream Official
    - julia -e 'using InteractiveUtils; versioninfo()'
    - julia-1 -e 'using InteractiveUtils; versioninfo()'
    - julia-1.0 -e 'using InteractiveUtils; versioninfo()'
    - julia-latest -e 'using InteractiveUtils; versioninfo()'
